---
  - name: demo for check mode 
    hosts: all
    vars:
      - datafile : /var/www/html/star.html
    tasks:
      - name: create a file on remote
        check_mode: no
        copy:
          content: "main system api" 
          dest: "{{ datafile }}"

      - name: set file prop 
        file:
          dest: "{{ datafile }}" 
          owner: root
          group: root
