--- 
  - name: debug demo
    hosts: all 

    tasks:
      - name: Run UPtime
        shell: /usr/bin/uptime
        register: aaa

      - name: display result
        debug:
          var: aaa
          verbosity: 1 

