---
 - name: generate hosts name
   hosts: all
   become: yes
   gather_facts: true
   tasks:
    - name: loop over inventory
      template: 
                   src: files/hosts.j2
                   dest: /etc/myhosts
                   owner: root
                   group: root
                   mode: 0644
      when: inventory_hostname in groups['webservers']
