---
- name: Create multiple local users
  hosts: webservers 
  vars_files:
    - vars/users_vars.yml 
  handlers: 
    - name: Restart SSHD
      service: 
        name: sshd
        state: restarted 

  tasks: 

    - name: Add WebAdmin Group 
      group:
        name: webadmin 
        state: present

    - name: Add users
      user:
        name: "{{ item.username }}"
        groups: webadmin
      loop: "{{ users }}"

    - name: Add Authorized Keys 
      authorized_key: 
        user: "{{ item.username }}"
        key: "{{ lookup('file', 'files/'+ item.username + '.key.pub' }}"
      loop: "{{ users }}"

    - name: Modify Sudo settings 
      copy: 
        content: "%webadmin ALL=(ALL) NOPASSWD: ALL"
        dest: /etc/sudoers.d/webadmin
        mode: 0440

    - name : Disable root login vis SSH 
      lineinfile:
        dest: /etc/sshd/sshd_config 
        regexp: "^PermitRootLogin"
        line: "PermitRootLogin no"
      notify: "Restart SSHD" 
