- hosts: all
  vars:
    users: 
      bjones: 
        fname: Bob
        lname: Jones
        hdir: /home/bjones
  

  tasks: 
  - name: Calling User Name from Array using dot
    debug: 
      msg: user first name is {{ users.bjones.fname }}

  - name: Calling User Name from Array using dot gets {{ users.bjones.lname }} 
    debug: 
      msg: user lastname is {{ users.bjones.lname }}
  
  - name: Calling User Home Dir from Array using dot gets {{ users.bjones.hdir }} 
    debug: 
      msg: user home dir is {{ users.bjones.hdir }}
  
  - name: Calling User Name from Array using dot gets {{ users.bjones.lname }} 
    debug: 
      msg: calling all= username is {{ users.bjones.fname }} {{ users.bjones.lname}} and home dir is {{ users.bjones.hdir }} 
