---
- name : Host_Vars Example 
  hosts: webserver

  tasks: 
  - name: Calling variable from group_var package 
    debug: 
      msg: "{{ package }}"

  - name: Calling another variable from group_var fire 
    debug: 
      msg: "{{ fire }}"
