---
- name: Install a package and print the result (specific) 
  hosts: servera.lab.example.com
  tasks: 
    - name: Install the package 
      yum:
        name: autofs
        state: installed 
      register: my_return

    - debug:
        msg: >
         The result of installation is= {{ my_return.msg }} 
