---
dependencies: []

galaxy_info:
  author: geerlingguy
  description: hdparm installation and configuration for Linux.
  company: "Midwestern Mac, LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.0
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - system
    - disk
    - hdparm
