---
# tasks file for apache
 - name: install httpd and firewalld 
   yum:
       name: "{{ item }}"
       state: present
   loop:
       - httpd
       - firewalld

 - name: start and enable service 
   service:
        name: "{{ item }}" 
        enabled: true
        state: started
   loop:
       - httpd
       - firewalld 

 - name: Add http to firewall 
   firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes
   notify: restart firewalld

 - name: push index.html 
   template:
           src: index.html.j2
           dest: /var/www/html/index.html
           owner: root
           group: root
           mode: 0644
   notify: restart httpd 
