---
  - name: NIC Config
    hosts: webservers 
    vars:
     - netif : ""

    pre_tasks:
    - set_fact:
        netif : "{{ item }}"
      when:  hostvars[inventory_hostname]['ansible_'~item]['ipv4']['address'] is not defined
      with_items:
        - "{{ ansible_interfaces }}"

    tasks:
    - name:  RHEL NET ROLE 
      include_role:
         name: rhel-system-roles.network
      when:  netif != "" 
