---
dependencies:
  - geerlingguy.svn
  - geerlingguy.git

galaxy_info:
  author: geerlingguy
  description: Svn2Git VCS conversion software for Linux.
  company: "Midwestern Mac, LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - development
    - svn
    - subversion
    - vcs
    - git
    - convert
    - svn2git
