---
- name: check users on remote hosts  
  hosts: all
  gather_facts: no 


  tasks: 
    - name: Using loop to run thru many list 
      user:
        name: "{{ item.name }}" 
        state: present
        groups: "{{ item.groups }}" 
      loop: 
        - name: root
          groups: root
        - name: student
          groups: wheel 
