---
- name: Database Setup play
  hosts: database_hosts
  vars:
    supported_distros:
      - RedHat
    min_ram_size_bytes: 512000
  tasks:
    - name: Install A Database on allowed hosts.
      include_tasks: "{{ ansible_distribution }}_database_tasks.yml"
      when:
        - ansible_distribution in supported_distros
        - ansible_memtotal_mb*1024*1024 >= min_ram_size_bytes

    - name: Print a message for unsupported Distros
      debug:
        msg: >
          {{ inventory_hostname }} is not one of the supported
          distributions ({{ supported_distros }})
      when: ansible_distribution not in supported_distros

    - name: Print a message for insufficient system requirements.
      debug:
        msg: >
          {{ inventory_hostname }} does not meet the minimum
          RAM requirements.
      when: ansible_memtotal_mb*1024*1024 < min_ram_size_bytes
