---
dependencies: []

galaxy_info:
  author: geerlingguy
  description: "Samba for RHEL/CentOS."
  company: "Midwestern Mac, LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
        - 6
        - 7
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - networking
    - system
    - samba
    - windows
    - filesystem
    - fileshare
    - sharing
    - files
