---
- name: Schedule at task
  hosts: all
  become: true
  become_user: devops 

  tasks:
    - name: Create date and time file 
      at:
        command: "date > ~/my_at.test\n"
        count: 1
        unit: minutes
        unique: yes
        state: present 
