---
- name: Using fail module
  hosts: all 
  tasks: 
    - name: Check if /etc/kdump.conf file exists 
      stat:
        path: /etc/kdump.confk
      register: lock 

    - name: Fail if the file exists 
      assert:
        that:
          - not lock.stat.exists 

    - name: Run some command 
      command: uptime
      register: out

    - debug:
        var: out.stdout
