---
- name: Converge
  hosts: all
  become: true

  vars:
    php_enable_webserver: false

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

    - name: Add repository for PHP 7.0 (Ubuntu).
      apt_repository: repo='ppa:ondrej/php'
      when: ansible_distribution == "Ubuntu" and ansible_distribution_version != "16.04"

  roles:
    - role: geerlingguy.php
    - role: geerlingguy.drupal-console
