---
- name: Converge
  hosts: all
  become: true

  vars:
    php_enable_webserver: false
    drupal_console_keep_updated: true

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - role: geerlingguy.php
    - role: geerlingguy.drupal-console
