---
- hosts: serverb.lab.example.com

  tasks: 
   - name: calling variable for servera
     debug:
       msg: "{{ package }}" 
  
   - name: calling variable for servera
     debug:
       msg: "{{ fire }}" 

...
