---
- hosts: servera.lab.example.com
  vars:
    unix: 
      - ibm
      - mac
      - solaris
      - hpux

  tasks:
  - name: Calling variable by array
    debug: 
      msg: 
        - "{{ unix[1] }}" 
        - "{{ unix[0] }}" 
        - "{{ unix[3] }}" 
        - "{{ unix[2] }}" 
